### ISSUE TITLE
Shader version too old in tests on modern OS X

### ISSUE THREAD

**Issue by Keno** [JuliaGL/GLAbstraction.jl#1]
```
#version 130
```

gives an error on OS X because the shader version is too old. Probably should use the same trick as in other places to set the shader version.

**Comment by ikirill** [comment]
I believe OSX, by default, gives a very old version of OpenGL API, and one needs to request a recent OpenGL API version explicitly: http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context
