### ISSUE TITLE
Warnings in current Julia head

### ISSUE THREAD

**Issue by ikirill** [JuliaGL/GLAbstraction.jl#10]
I get this warning with a Julia nightly build, in gluniform.

    WARNING: [a] concatenation is deprecated; use [a;] instead
     in depwarn at /opt/software/Julia-0.4.0-dev-32aee08d0b.app/Contents/Resources/julia/lib/julia/sys.dylib
     in oldstyle_vcat_warning at /opt/software/Julia-0.4.0-dev-32aee08d0b.app/Contents/Resources/julia/lib/julia/sys.dylib
     in gluniform at no file
     in ***

I'm not sure where it's coming from.

**Comment by SimonDanisch** [comment]
Yup... this is to be expected..did you check out master of GLAbstraction? I think i fixed it there....

**Comment by ikirill** [comment]
I did `Pkg.checkout(...)` and the warning is fixed. Must be something else that broke my program.
