### ISSUE TITLE
How to correctly use glGenBuffers()

### ISSUE THREAD

**Issue by Gnimuc** [JuliaGL/GLAbstraction.jl#11]
I find these code in GLTypes.jl:
```
type GLBuffer{T <: Real, Cardinality}
    id::GLuint
    length::Int
    buffertype::GLenum
    usage::GLenum

    function GLBuffer(ptr::Ptr{T}, size::Int, buffertype::GLenum, usage::GLenum)
        @assert size % sizeof(T) == 0
        _length = div(size, sizeof(T))
        @assert _length % Cardinality == 0
        _length = div(_length, Cardinality)

--->    id = glGenBuffers()      # I don't know why this line could run correctly
        glBindBuffer(buffertype, id)
        glBufferData(buffertype, size, ptr, usage)
        glBindBuffer(buffertype, 0)

        obj = new(id, _length, buffertype, usage)
    end
end
```
but the only definition of glGenBuffer() in ModernGL.jl is
```
function glGenBuffers(n, buffers)
	ccall(@getFuncPointer("glGenBuffers"), Void, (GLsizei, Ptr{GLuint}), n, buffers)
end
```
Just got confused, if I run `id = glGenBuffers()`, a mismatching error will occur.  Am I missing something?

**Comment by SimonDanisch** [comment]
Hi there,
you missed the definition in [GLExtendedFunctions.jl](https://github.com/JuliaGL/GLAbstraction.jl/blob/f9bad4d42d9d4ff5cafaa9f69ad31e7fb8c7c6ce/src/GLExtendedFunctions.jl#L88)
I've started overloading functions that are difficult to use with julia, for example functions that take pointers to numbers and then mutate them.
As I don't have any documentation, feel free to ask me any question here or per mail... I don't have the patience to write a documentation right now, but I'd love to see people use this package ;)

**Comment by Gnimuc** [comment]
Many thanks, finally I got my code to work. As I'm new to OpenGL, I think I could give your some useful feedback when you plan to complete the documents in the future.

**Comment by SimonDanisch** [comment]
Cool, that would be awesome =) Any feedback is more than welcome!
