### ISSUE TITLE
Use finalizers to garbage collect allocated opengl resources

### ISSUE THREAD

**Issue by richcole** [JuliaGL/GLAbstraction.jl#17]
It would be handy if functions that allocate opengl resources register a finalizer that will return the items ones they're no longer in scope.

I'm still pretty new to Julia, but perhaps something like the following (sorry for the javaisms I'm still learning, idea is the register a finalizer in the constructor for the buffer object).

type GLBuffer
  idPtr::Ptr{GLuint}  
  id

  function release()
    if id != nothing then
      glDeleteBuffers(1, idPtr)
      id = nothing
    end
  end

  function GLBuffer() 
    idPtr = GLuint[0]
    glGenBuffers(1, idPtr)
    glCheckError("calling glGenBuffers")
    id = unsafe_load(idPtr)
    finalize(this, release)
  end

end

I'm guessing you can write 

vbo = GLBuffer()
glBindBuffer(GL_ARRAY_BUFFER, vbo.id)

I've found this sort of thing is pretty useful in java and clojure opengl programs. The garbage collector is mostly good enough to clean up.

**Comment by SimonDanisch** [comment]
Hi, 
yeah thats something I experimented with, but it did not work well... As GLFW cleans up everything after me, I haven't further looked into it.
I might give it another shot later.

Best,
Simon

**Comment by SimonDanisch** [comment]
Should be mostly done now ;)
