### ISSUE TITLE
Pkg.test fails on FreeBSD with Julia 0.5.0

### ISSUE THREAD

**Issue by ko56** [JuliaGL/GLAbstraction.jl#58]
I can't tell if this is a problem with GLAbstraction or with FileIO:

julia> Pkg.test("GLAbstraction")
INFO: Computing test dependencies for GLAbstraction...
INFO: No packages to install, update or remove
INFO: Testing GLAbstraction
ERROR: LoadError: MethodError: Cannot `convert` an object of type FileIO.File{FileIO.DataFormat{:GLSLShader}} to an object of type GLAbstraction.Shader
This may have arisen from a call to the constructor GLAbstraction.Shader(...),
since type constructors fall back to convert methods.
 in load(::FileIO.File{FileIO.DataFormat{:GLSLShader}}) at /usr/home/ko/.julia/v0.5/GLAbstraction/src/GLShader.jl:77
 in #load#13(::Array{Any,1}, ::Function, ::String) at /usr/home/ko/.julia/v0.5/FileIO/src/loadsave.jl:45
 in macro expansion; at /usr/home/ko/.julia/v0.5/GLAbstraction/test/runtests.jl:34 [inlined]
 in anonymous at ./<missing>:?
 in _init at /usr/local/lib/julia/sys.so:? (repeats 5 times)
while loading /usr/home/ko/.julia/v0.5/GLAbstraction/test/runtests.jl, in expression starting on line 11

**Comment by SimonDanisch** [comment]
Nope this is a problem with my laziness ;) I treat GLAbstraction's tests really badly, since I'm testing it way more thorough via GLVisualize.
Let me clean up the tests nevertheless!

**Comment by ko56** [comment]
Ah, thanks.  My ultimate goal is to get GLVisualize working, so I'm 
going step-by-step.
