### ISSUE TITLE
glTexImage 2D: width too large. Width: 256

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLAbstraction.jl#6]
I started getting the following.  Reverting GLText 1 commit fixes it.

glTexImage 2D: width too large. Width: 256
while loading In[2], in expression starting on line 10

 in glTexImage at /Users/solver/.julia/v0.3/GLAbstraction/src/GLExtendedFunctions.jl:162
 in Texture at /Users/solver/.julia/v0.3/GLAbstraction/src/GLTexture.jl:61
 in Texture at /Users/solver/.julia/v0.3/GLAbstraction/src/GLTexture.jl:209
 in Texture at /Users/solver/.julia/v0.3/GLAbstraction/src/GLTexture.jl:228
 in Texture at /Users/solver/.julia/v0.3/GLAbstraction/src/GLTexture.jl:252
 in GLFont at /Users/solver/.julia/v0.3/GLText/src/types.jl:95
 in inittext at /Users/solver/.julia/v0.3/GLText/src/GLText.jl:15
 in init_glutils at /Users/solver/.julia/v0.3/GLAbstraction/src/GLInit.jl:12
 in createwindow at /Users/solver/.julia/v0.3/GLWindow/src/reactglfw.jl:401
 in createdisplay at /Users/solver/.julia/v0.3/GLPlot/src/GLPlot.jl:51
 in glsurf at /Users/solver/.julia/v0.3/ApproxFun/src/Plot/GLPlot.jl:57
 in surf at /Users/solver/.julia/v0.3/ApproxFun/src/Plot/Plot.jl:78
 in plot at /Users/solver/.julia/v0.3/ApproxFun/src/Plot/Plot.jl:191
 in timeevolution at /Users/solver/.julia/v0.3/ApproxFun/src/Extras/show.jl:141

**Comment by SimonDanisch** [comment]
Thanks for this!
I'm not entirely sure, how this happens.
But I fixed something in GLText which was definitely wrong and might solve this as well. If you have some time, try out GLText master.

**Comment by dlfivefifty** [comment]
Maybe I should add a unit test for ApproxFun + GLPlot so that these issues are caught automatically?  I.e., before I’m in the middle of a demo :)

**Comment by SimonDanisch** [comment]
Well maybe i should start taking GLPlot a little more serious!
The issue is, that my tagged version didn't work and I haven't made a new tag...
Which means you need to work on master, which I don't treat carefully enough, correct?
But tests are always a good thing!

**Comment by dlfivefifty** [comment]
I think the issue is that GLText wasn’t tagged as 0.0.4

	Also, I don’t know what official “good practice” is for open source projects, but I suspect the goal should be for “master” to not break.  Personally, I (sometimes) try to create a new branch if I think the changes will break master.  (Though I break ApproxFun’s master all the time so I’m not one to talk!!)
