### ISSUE TITLE
Examples fail to run because shader string macros do not compile

### ISSUE THREAD

**Issue by biogeo** [JuliaGL/GLAbstraction.jl#65]
When I attempt to run any of the examples provided with the package, they generate an error at the first nonstandard string literal defining vertex shaders. E.g., in `simple_triangle.jl`, line 6:

```
const vsh = vert"""
{{GLSL_VERSION}}
in vec2 position;

void main(){
	gl_Position = vec4(position, 0, 1.0);
}
"""
```

It looks like the `@vert_str` macro doesn't try to parse the `{{GLSL_VERSION}}` template value, and possibly this could be fixed just by using `LazyShader` instead of `Shader` in the macro, but I'm not clear if the template values were intended for shader program files only or also for the string literals.

**Comment by SimonDanisch** [comment]
Sorry about that, the examples are not very well tested.
I will look into it tomorrow!

**Comment by SimonDanisch** [comment]
finally got around to: https://github.com/JuliaGL/GLAbstraction.jl/pull/66
