### ISSUE TITLE
Fails to precompile on Julia 0.6

### ISSUE THREAD

**Issue by mobius-eng** [JuliaGL/GLAbstraction.jl#68]
Importing `GLAbstraction` in Julia 0.6 results in the following error:

```
INFO: 
Precompiling module GLAbstraction.
WARNING: could not import Base.call into GLAbstraction
WARNING: both GeometryTypes and FixedSizeArrays export "Mat"; uses of it in module GLAbstraction must be qualified
ERROR: LoadError: LoadError: 
UndefVarError: Mat not defined
Stacktrace:
 [1] 
include_from_node1(::String) at .\loading.jl:539
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:539
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\alexe_000\.julia\v0.6\GLAbstraction\src\composition.jl, in expression starting on line 76
while loading C:\Users\alexe_000\.julia\v0.6\GLAbstraction\src\GLAbstraction.jl, in expression starting on line 57
```

Tested on the master branches of `GLAbstraction`, `GeometryTypes` and `FixedSizeArrays`

**Comment by SimonDanisch** [comment]
Yes, 0.6 is not supported right now :( im trying to work towards it, problem is, that the 0.6 compatible branch is 0.6 only.. So i need to figure out how to release that!

**Comment by mobius-eng** [comment]
Thanks, I saw afterwards that there is 0.6 branch... Now, the problem for me is that I'm trying to use GLVisualize --- I am going to see if it will work with 0.6 branch.

**Comment by SimonDanisch** [comment]
No! ;) 
You need to checkout:

GLAbstraction -> sd/staticarrays
GLVisualize -> sd/staticarrays
GeometryTypes -> master
GLWindow -> sd/staticarrays
MeshIO -> sd/staticarrays

This is not tested very well, though. I'd recommend using 0.5 or waiting for me to actually clean this up!

**Comment by Ken-B** [comment]
Any update on this with julia 0.6 released? Are the checkouts still needed? Thanks! ;)

**Comment by PinkMushroom** [comment]
hi
i'd really like to see this work with 0.6 also

**Comment by SimonDanisch** [comment]
Fixed in https://github.com/JuliaLang/METADATA.jl/pull/10230
