### ISSUE TITLE
GLVertexArray should keep its bufferDict at construction

### ISSUE THREAD

**Issue by ikirill** [JuliaGL/GLAbstraction.jl#8]
GLVertexArray should keep its bufferDict at construction (https://github.com/SimonDanisch/GLAbstraction.jl/blob/master/src/GLTypes.jl#L145), because it is helpful to be able to call glBufferData with new data, for a specific vertex attribute, for an existing vertex array.

**Comment by SimonDanisch** [comment]
done long time ago ;) I should really be more diligent with issue tracking!
