### ISSUE TITLE
Geometry shaders are missing?

### ISSUE THREAD

**Issue by ikirill** [JuliaGL/GLAbstraction.jl#9]
It seems geometry shaders are not yet implemented, and GLProgram seems to assume that only vertex and fragment shaders will be used. Since geometry shaders are optional, there should be a way to attach a geometry shader to a GLProgram without manipulating the GLProgram object by hand.

**Comment by SimonDanisch** [comment]
Yes, this is quite a problem. The thing is, I just add what I need for the
moment... For myself, I actually gave up on geometry shaders and want to
emulate them rather via OpenCL. But nevertheless, an overhaul of the shader
code is about time, as its quite messy. I soon want to allow for more
flexible linking of functions  into shaders and program pipelines. But I
dont know when i will get around to this...

**Comment by ikirill** [comment]
> ...The thing is, I just add what I need for the moment...

I'm completely okay with that. I can get at the underlying variables myself and then use OpenGL functions, so that's not really such a big problem for me, so long as there is enough information in the "abstracted" objects to get at the raw variables.

**Comment by SimonDanisch** [comment]
All kinds of shader are supported now
